### ISSUE TITLE
Add support for Tone Analyzer

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-wrapper#11]
Add Tone Analyzer support

**Comment by germanattanasio** [comment]
@herchu can you please review the implementation? I will be finishing with `/synonym` tomorrow and adding some tests cases too.

**Comment by herchu** [comment]
Looks good. My comments:

* The default path 
private static final String URL ...
should be /tone-analyzer-experimental (not -beta)

* The scorecard name in getTone() should be optional. Or, default to the default scorecard name if null. We should define "email" as the default scorecard in the wrapper, somewhere in the constants, to simplify usage (This is intended for future growth of the service, but right now that is the only value, so it makes no sense for users to be aware of this).

* getSynynyms() -> getSynonyms()

With this, I think we have a first version!

**Comment by germanattanasio** [comment]
Can you please take a look at the POJOs in `tone_analyzer.v1.model` and make sure the javadoc is complete?  I love the idea of having a pull request with javadoc for the service and the model classes :ear:
