### ISSUE TITLE
Concept Expansion Error

### ISSUE THREAD

**Issue by scarrdi** [watson-developer-cloud/java-wrapper#12]
Issue with a call from the source of the wrapper.

![ce_error](https://cloud.githubusercontent.com/assets/13457503/8836014/0f014976-308c-11e5-981e-b7803386318e.PNG)
![ce_code](https://cloud.githubusercontent.com/assets/13457503/8836015/0f8bd226-308c-11e5-8546-f2d23fcbfc2d.PNG)

**Comment by germanattanasio** [comment]
Fixed in 499babd5d283765d9a2e2f2c2c17f371ec3f407d
