### ISSUE TITLE
Missing methods/variables in Natural Language Classifier Model (Classifier.java)

### ISSUE THREAD

**Issue by scprotz** [watson-developer-cloud/java-wrapper#18]
This class is missing the following variables and accessors as per the API:

name (getName(), setName())
created (getCreated(), setCreated())
language (getLanguaged(), setLanguage())

Easy to fix (I just added the variables and methods to my own clone).

**Comment by germanattanasio** [comment]
@alseddnm I know you are working on the test cases but can you put this on the list?
