### ISSUE TITLE
Uploading dialog file using java wrapper returns BadRequestException

### ISSUE THREAD

**Issue by jorge683** [watson-developer-cloud/java-wrapper#38]
Hi

When trying to upload an XML file to the dialog service to create a dialog I receive an error with the following message:

[error] c.i.w.d.s.WatsonService - HTTP Status: 400, message: Failed to import file. Possibly due to corrupt or invalid file or system error. - Input length (with padding) not multiple of 16 bytes

I am not sure why, I suspect that is due to a bad header sent in the request, If I use the dialog tool same file works flawlessly, but through the java wrapper does not.

**Comment by germanattanasio** [comment]
Hi @jorge683 can we get the xml you are using? I'm testing the `create` method and it seems to be working for me.

**Comment by jorge683** [comment]
Hi

I'm using one of the sample files provided (https://raw.githubusercontent.com/watson-developer-cloud/dialog-tool/master/dialogs/pizza_sample.xml). 
Can you include sample on how you call the createDialog API function (I am not able to find a create method)?

Thank you.

**Comment by germanattanasio** [comment]
Hi @jorge683, I just tried:

```
service = new DialogService();
service.setUsernameAndPassword("USERNAME","PASSWORD");
service.setEndPoint("https://gateway.watsonplatform.net/dialog-beta/api");

File dialogFile = new File("pizza_sample.xml");
Dialog newDialog = service.createDialog("my-pizza-dialog", dialogFile);
```
And it's working. Make sure you use `https://gateway.watsonplatform.net/dialog-beta/api` because by default the service will try to use the experimental version which is `https://gateway.watsonplatform.net/dialog-experimental/api` and it doesn't support xml.
