### ISSUE TITLE
Invalid use of BasicClientConnManager: connection still allocated

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-wrapper#8]
Currently the `execute()` method is single thread and try to use only one HTTP connection. This is a big problem if the wrapper is being used in a multi-thread environment so we need to add a http connection pool.

See:

* http://stackoverflow.com/questions/14866362/invalid-use-of-basicclientconnmanager-connection-still-allocated
* http://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html#d5e619
* http://stackoverflow.com/questions/4612573/exception-using-httprequest-execute-invalid-use-of-singleclientconnmanager-c

**Comment by germanattanasio** [comment]
I'm going to fully read the `InputStream` and that should be enough to close the http connection. I may also include a connection manager to also handle a pool of http connections.

I'm currently looking at: http://grepcode.com/file/repo1.maven.org/maven2/org.apache.httpcomponents/httpcore/4.0.1/org/apache/http/util/EntityUtils.java

**Comment by germanattanasio** [comment]
More work on 5f4420efa799b65de0c5f1789f0bf75bfb296452

**Comment by aarora91** [comment]
Thanks. Just tested this with the update. Works fine.
