### ISSUE TITLE
UTF-8 compatible

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-wrapper#9]
Looks like the wrapper is not encoding the requests as UTF-8.

Specially for the dialog service when we try to update the profile

**Comment by aarora91** [comment]
Need to check with John Zakos to see if it's a WDS issue. The user input gets displayed correctly in the response json but the WDS response text is not.

**Comment by germanattanasio** [comment]
Any update onthis @aarora91 ?

**Comment by aarora91** [comment]
None so far. I have checked with John and he believes it's not a WDS issue. Dan O' Connor is looking into this. I'll let you know if we feel it's an issue with the SDK code in particular. Thanks!

**Comment by germanattanasio** [comment]
Fixed in 258439c4284d9a716f612c028c288cce8701ab95

**Comment by germanattanasio** [comment]
I tested and the wrapper has support for UTF-8
